---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spendcontrol-microprofile
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.ibm.spendcontrol
  name: spendcontrol-microprofile
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: spendcontrol-microprofile
      provider: fabric8
      group: com.ibm.spendcontrol
  template:
    metadata:
      labels:
        app: spendcontrol-microprofile
        provider: fabric8
        version: 1.0.0-SNAPSHOT
        group: com.ibm.spendcontrol
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: spendcontrol-microprofile:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: thorntail-v2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
